#!/bin/bash

# Get the current version from the version file
current_version=$(grep 'version=' roborally/version | cut -d '=' -f 2)

# Check if the current version is already tagged
if git rev-parse "$current_version" >/dev/null 2>&1; then
    echo "Version $current_version already exists. Skipping tagging."
else
    # Tag the latest commit with the current version and push the tag
    git tag -a "$current_version" -m "Release $current_version"
    git push origin HEAD
    git push origin "$current_version"

    echo "Pushed new version: $current_version"
fi
