@startuml
skinparam linetype ortho

class Player
class Robot
class Start_Board
class Game_Board
class Energy_Reserve
class Player_Energy
class Upgrade_Shop
class Cards
class Programming_Deck
class Tokens
class Tiles
class PlayerMat
class Checkpoints
class Energy_Cubes
class Priority_Antenna
class Discard_Pile

'Player relations
Player " 1 " -- " 1 " Robot: programs
Player " 1 " -u- " 1 " PlayerMat

'Player mat relations'
PlayerMat " 1 " *-- " 1 " Programming_Deck
PlayerMat " 1 " *-- " 1 " Player_Energy
PlayerMat " 1 " *-- " 1 " Discard_Pile
Programming_Deck " 1 " o-- " 1..* " Cards
Player_Energy " 1 " o-- " 0..* " Energy_Cubes
Discard_Pile " 1 " o-- " 1..* " Cards
PlayerMat " 1 " -- " 0..* " Tokens 

'Off board relations'
Energy_Reserve " 1 " o-- " 0..* " Energy_Cubes
Upgrade_Shop " 1 " o-- " 0..* " Cards

'Board relations'
Robot " 1 " -- " 1 " Tiles: lands on

Game_Board " 1 " *-- " 1..* " Tiles
Game_Board " 1 " -- " 1..* " Checkpoints 

Start_Board " 1 " *-- " 1..* " Tiles
Start_Board " 1 " *-- " 1 " Priority_Antenna

@enduml