@startuml

[*] --> Menu
Menu : User specify the parameters of the game
Menu --> Programming : Start game
Programming : Each player program their robot
Programming --> Ready : Finish programming
Ready : All players have programmed thir robot
Ready --> ExecutingNextInstruction
ExecutingNextInstruction : The next instruction from each player will be executed 
ExecutingNextInstruction --> ApllyingBordEffects
ApllyingBordEffects : conveyerbelts and other effects will be executed
ApllyingBordEffects --> ExecutingNextInstruction
ApllyingBordEffects --> Programming : Finished last Instruction
ApllyingBordEffects --> ShowingGameStatus : game is finished
ShowingGameStatus : The game is over and the statistics will be displayed
ShowingGameStatus --> Menu : Exit game

@enduml