name: Versioning

on:
  push:
    branches:
      - main
      - dev
      - '**'
  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag within branch context
        id: get_latest_tag
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1 --grep="^v[0-9]\+\.[0-9]\+\.[0-9]\+$" --remotes=origin/$branch) 2>/dev/null || echo "v0.0.0")
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Determine increment type
        id: increment_type
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=increment_type::major"
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "::set-output name=increment_type::minor"
          else
            echo "::set-output name=increment_type::patch"
          fi

      - name: Increment version
        id: increment_version
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          increment_type=${{ steps.increment_type.outputs.increment_type }}
          if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-.+)?$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            suffix=${BASH_REMATCH[4]}

            if [[ $increment_type == "major" ]]; then
              new_major=$((major + 1))
              new_version="v$new_major.0.0$suffix"
            elif [[ $increment_type == "minor" ]]; then
              new_minor=$((minor + 1))
              new_version="v$major.$new_minor.0$suffix"
            else
              new_patch=$((patch + 1))
              new_version="v$major.$minor.$new_patch$suffix"
            fi

            echo "New version: $new_version"
            echo "::set-output name=new_version::$new_version"
          else
            echo "Invalid tag format. Expected format: v<major>.<minor>.<patch>[-suffix]"
            exit 1
          fi

      - name: Log debug info
        run: |
          echo "Latest tag: ${{ steps.get_latest_tag.outputs.latest_tag }}"
          echo "Increment type: ${{ steps.increment_type.outputs.increment_type }}"
          echo "New version: ${{ steps.increment_version.outputs.new_version }}"

      - name: Update version file
        run: echo "version=${{ steps.increment_version.outputs.new_version }}" > roborally/version

      - name: Commit version increment
        run: |
          git add roborally/version
          git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"
          git push origin HEAD

      - name: Create new tag
        run: |
          git tag -a ${{ steps.increment_version.outputs.new_version }} -m "Release ${{ steps.increment_version.outputs.new_version }}"
          git push origin ${{ steps.increment_version.outputs.new_version }}
